/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Channel0 */
#define Channel0_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel0_0_INBUF_ENABLED 0u
#define Channel0_0_INIT_DRIVESTATE 0u
#define Channel0_0_INIT_MUXSEL 0u
#define Channel0_0_INPUT_SYNC 2u
#define Channel0_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel0_0_NUM 0u
#define Channel0_0_PORT GPIO_PRT9
#define Channel0_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel0_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Channel0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel0_INBUF_ENABLED 0u
#define Channel0_INIT_DRIVESTATE 0u
#define Channel0_INIT_MUXSEL 0u
#define Channel0_INPUT_SYNC 2u
#define Channel0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel0_NUM 0u
#define Channel0_PORT GPIO_PRT9
#define Channel0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Channel1 */
#define Channel1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel1_0_INBUF_ENABLED 0u
#define Channel1_0_INIT_DRIVESTATE 0u
#define Channel1_0_INIT_MUXSEL 0u
#define Channel1_0_INPUT_SYNC 2u
#define Channel1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel1_0_NUM 1u
#define Channel1_0_PORT GPIO_PRT9
#define Channel1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Channel1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel1_INBUF_ENABLED 0u
#define Channel1_INIT_DRIVESTATE 0u
#define Channel1_INIT_MUXSEL 0u
#define Channel1_INPUT_SYNC 2u
#define Channel1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel1_NUM 1u
#define Channel1_PORT GPIO_PRT9
#define Channel1_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Channel2 */
#define Channel2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel2_0_INBUF_ENABLED 0u
#define Channel2_0_INIT_DRIVESTATE 0u
#define Channel2_0_INIT_MUXSEL 0u
#define Channel2_0_INPUT_SYNC 2u
#define Channel2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel2_0_NUM 2u
#define Channel2_0_PORT GPIO_PRT9
#define Channel2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Channel2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel2_INBUF_ENABLED 0u
#define Channel2_INIT_DRIVESTATE 0u
#define Channel2_INIT_MUXSEL 0u
#define Channel2_INPUT_SYNC 2u
#define Channel2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel2_NUM 2u
#define Channel2_PORT GPIO_PRT9
#define Channel2_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Channel3 */
#define Channel3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel3_0_INBUF_ENABLED 0u
#define Channel3_0_INIT_DRIVESTATE 1u
#define Channel3_0_INIT_MUXSEL 3u
#define Channel3_0_INPUT_SYNC 2u
#define Channel3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel3_0_NUM 3u
#define Channel3_0_PORT GPIO_PRT9
#define Channel3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Channel3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Channel3_INBUF_ENABLED 0u
#define Channel3_INIT_DRIVESTATE 1u
#define Channel3_INIT_MUXSEL 3u
#define Channel3_INPUT_SYNC 2u
#define Channel3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel3_NUM 3u
#define Channel3_PORT GPIO_PRT9
#define Channel3_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
