/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Button */
#define Button_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_0_INBUF_ENABLED 1u
#define Button_0_INIT_DRIVESTATE 0u
#define Button_0_INIT_MUXSEL 0u
#define Button_0_INPUT_SYNC 2u
#define Button_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_0_NUM 4u
#define Button_0_PORT GPIO_PRT0
#define Button_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Button_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_INBUF_ENABLED 1u
#define Button_INIT_DRIVESTATE 0u
#define Button_INIT_MUXSEL 0u
#define Button_INPUT_SYNC 2u
#define Button_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_NUM 4u
#define Button_PORT GPIO_PRT0
#define Button_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* RedLight */
#define RedLight_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RedLight_0_INBUF_ENABLED 0u
#define RedLight_0_INIT_DRIVESTATE 1u
#define RedLight_0_INIT_MUXSEL 3u
#define RedLight_0_INPUT_SYNC 2u
#define RedLight_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RedLight_0_NUM 3u
#define RedLight_0_PORT GPIO_PRT0
#define RedLight_0_SLEWRATE CY_GPIO_SLEW_FAST
#define RedLight_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define RedLight_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define RedLight_INBUF_ENABLED 0u
#define RedLight_INIT_DRIVESTATE 1u
#define RedLight_INIT_MUXSEL 3u
#define RedLight_INPUT_SYNC 2u
#define RedLight_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define RedLight_NUM 3u
#define RedLight_PORT GPIO_PRT0
#define RedLight_SLEWRATE CY_GPIO_SLEW_FAST
#define RedLight_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* GreendLight */
#define GreendLight_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreendLight_0_INBUF_ENABLED 0u
#define GreendLight_0_INIT_DRIVESTATE 1u
#define GreendLight_0_INIT_MUXSEL 3u
#define GreendLight_0_INPUT_SYNC 2u
#define GreendLight_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreendLight_0_NUM 1u
#define GreendLight_0_PORT GPIO_PRT1
#define GreendLight_0_SLEWRATE CY_GPIO_SLEW_FAST
#define GreendLight_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define GreendLight_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define GreendLight_INBUF_ENABLED 0u
#define GreendLight_INIT_DRIVESTATE 1u
#define GreendLight_INIT_MUXSEL 3u
#define GreendLight_INPUT_SYNC 2u
#define GreendLight_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define GreendLight_NUM 1u
#define GreendLight_PORT GPIO_PRT1
#define GreendLight_SLEWRATE CY_GPIO_SLEW_FAST
#define GreendLight_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
