/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Channel0 */
#define Channel0_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Channel0_0_INBUF_ENABLED 0u
#define Channel0_0_INIT_DRIVESTATE 1u
#define Channel0_0_INIT_MUXSEL 0u
#define Channel0_0_INPUT_SYNC 2u
#define Channel0_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel0_0_NUM 5u
#define Channel0_0_PORT GPIO_PRT9
#define Channel0_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel0_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Channel0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Channel0_INBUF_ENABLED 0u
#define Channel0_INIT_DRIVESTATE 1u
#define Channel0_INIT_MUXSEL 0u
#define Channel0_INPUT_SYNC 2u
#define Channel0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Channel0_NUM 5u
#define Channel0_PORT GPIO_PRT9
#define Channel0_SLEWRATE CY_GPIO_SLEW_FAST
#define Channel0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
